/*
 * Live Objects REST API Guide v2.13.3
 *
 * API description for Live Objects service
 *
 * API version: 2.13.3
 * Contact: liveobjects.support@orange.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package liveobjects

import (
	"encoding/json"
)

// TenantMonthMetrics struct for TenantMonthMetrics
type TenantMonthMetrics struct {
	Tenant *TenantExternalView `json:"tenant,omitempty"`
	// Statistics per month
	Months *[]MonthMetrics `json:"months,omitempty"`
}

// NewTenantMonthMetrics instantiates a new TenantMonthMetrics object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTenantMonthMetrics() *TenantMonthMetrics {
	this := TenantMonthMetrics{}
	return &this
}

// NewTenantMonthMetricsWithDefaults instantiates a new TenantMonthMetrics object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTenantMonthMetricsWithDefaults() *TenantMonthMetrics {
	this := TenantMonthMetrics{}
	return &this
}

// GetTenant returns the Tenant field value if set, zero value otherwise.
func (o *TenantMonthMetrics) GetTenant() TenantExternalView {
	if o == nil || o.Tenant == nil {
		var ret TenantExternalView
		return ret
	}
	return *o.Tenant
}

// GetTenantOk returns a tuple with the Tenant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantMonthMetrics) GetTenantOk() (*TenantExternalView, bool) {
	if o == nil || o.Tenant == nil {
		return nil, false
	}
	return o.Tenant, true
}

// HasTenant returns a boolean if a field has been set.
func (o *TenantMonthMetrics) HasTenant() bool {
	if o != nil && o.Tenant != nil {
		return true
	}

	return false
}

// SetTenant gets a reference to the given TenantExternalView and assigns it to the Tenant field.
func (o *TenantMonthMetrics) SetTenant(v TenantExternalView) {
	o.Tenant = &v
}

// GetMonths returns the Months field value if set, zero value otherwise.
func (o *TenantMonthMetrics) GetMonths() []MonthMetrics {
	if o == nil || o.Months == nil {
		var ret []MonthMetrics
		return ret
	}
	return *o.Months
}

// GetMonthsOk returns a tuple with the Months field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantMonthMetrics) GetMonthsOk() (*[]MonthMetrics, bool) {
	if o == nil || o.Months == nil {
		return nil, false
	}
	return o.Months, true
}

// HasMonths returns a boolean if a field has been set.
func (o *TenantMonthMetrics) HasMonths() bool {
	if o != nil && o.Months != nil {
		return true
	}

	return false
}

// SetMonths gets a reference to the given []MonthMetrics and assigns it to the Months field.
func (o *TenantMonthMetrics) SetMonths(v []MonthMetrics) {
	o.Months = &v
}

func (o TenantMonthMetrics) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Tenant != nil {
		toSerialize["tenant"] = o.Tenant
	}
	if o.Months != nil {
		toSerialize["months"] = o.Months
	}
	return json.Marshal(toSerialize)
}

type NullableTenantMonthMetrics struct {
	value *TenantMonthMetrics
	isSet bool
}

func (v NullableTenantMonthMetrics) Get() *TenantMonthMetrics {
	return v.value
}

func (v *NullableTenantMonthMetrics) Set(val *TenantMonthMetrics) {
	v.value = val
	v.isSet = true
}

func (v NullableTenantMonthMetrics) IsSet() bool {
	return v.isSet
}

func (v *NullableTenantMonthMetrics) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenantMonthMetrics(val *TenantMonthMetrics) *NullableTenantMonthMetrics {
	return &NullableTenantMonthMetrics{value: val, isSet: true}
}

func (v NullableTenantMonthMetrics) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenantMonthMetrics) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


