/*
 * Live Objects REST API Guide v2.12.2
 *
 * API description for Live Objects service
 *
 * API version: 2.12.2
 * Contact: liveobjects.support@orange.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package liveobjects
// Group struct for Group
type Group struct {
	// Date/time when group was first registered
	Created string `json:"created"`
	// Group description
	Description string `json:"description"`
	// Group identifier
	Id string `json:"id"`
	// Parent group identifier
	ParentId string `json:"parentId"`
	// Path
	Path string `json:"path"`
	// Path node
	PathNode string `json:"pathNode"`
	// Date/time when group status has been lastly updated
	Updated string `json:"updated"`
}
