/*
 * Live Objects REST API Guide v2.12.2
 *
 * API description for Live Objects service
 *
 * API version: 2.12.2
 * Contact: liveobjects.support@orange.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package liveobjects
// Thresholds body of sms connector limits
type Thresholds struct {
	// max of msisdn allow to register
	MaxMsisdn int32 `json:"maxMsisdn"`
	// max of sms received allow
	MaxSmsInPerDay int32 `json:"maxSmsInPerDay"`
	// max of sms send allow
	MaxSmsOutPerDay int32 `json:"maxSmsOutPerDay"`
	// max of tag allow to register
	MaxTags int32 `json:"maxTags"`
}
