/*
 * Live Objects REST API Guide v2.12.2
 *
 * API description for Live Objects service
 *
 * API version: 2.12.2
 * Contact: liveobjects.support@orange.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package liveobjects
// ConnectorAccounting struct for ConnectorAccounting
type ConnectorAccounting struct {
	Inventory map[string]int64 `json:"inventory,omitempty"`
	Traffic Traffic `json:"traffic,omitempty"`
}
