/*
 * Live Objects REST API Guide v2.12.2
 *
 * API description for Live Objects service
 *
 * API version: 2.12.2
 * Contact: liveobjects.support@orange.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package liveobjects
// TenantSettings struct for TenantSettings
type TenantSettings struct {
	Settings map[string]SettingsSection `json:"settings,omitempty"`
	TenantId string `json:"tenantId,omitempty"`
}
