/*
 * Live Objects REST API Guide v2.12.2
 *
 * API description for Live Objects service
 *
 * API version: 2.12.2
 * Contact: liveobjects.support@orange.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package liveobjects
// Polygon struct for Polygon
type Polygon struct {
	Coordinates [][][]float64 `json:"coordinates,omitempty"`
	Type string `json:"type,omitempty"`
}
