/*
 * Live Objects REST API Guide v2.12.2
 *
 * API description for Live Objects service
 *
 * API version: 2.12.2
 * Contact: liveobjects.support@orange.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package liveobjects
// TenantStatsWeb struct for TenantStatsWeb
type TenantStatsWeb struct {
	Properties map[string]string `json:"properties,omitempty"`
	// all statistics per day
	StatisticsPerDay map[string]map[string]ConnectorStatistics `json:"statisticsPerDay,omitempty"`
	// Statistics per month : number of distinct sources (lora, mqtt, datazone)
	StatisticsPerMonth map[string]map[string]ConnectorStatistics `json:"statisticsPerMonth,omitempty"`
	// The tenant Id
	TenantId string `json:"tenantId,omitempty"`
	// The tenant name
	TenantName string `json:"tenantName,omitempty"`
	// Aggregation of all statistics
	Total map[string]ConnectorStatistics `json:"total,omitempty"`
}
