/*
 * Live Objects REST API Guide v2.13.3
 *
 * API description for Live Objects service
 *
 * API version: 2.13.3
 * Contact: liveobjects.support@orange.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package liveobjects

import (
	"encoding/json"
)

// ConnectorStatusResponse struct for ConnectorStatusResponse
type ConnectorStatusResponse struct {
	// list all msisdn with status treated
	StatusPerMsisdn *map[string]string `json:"statusPerMsisdn,omitempty"`
}

// NewConnectorStatusResponse instantiates a new ConnectorStatusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectorStatusResponse() *ConnectorStatusResponse {
	this := ConnectorStatusResponse{}
	return &this
}

// NewConnectorStatusResponseWithDefaults instantiates a new ConnectorStatusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectorStatusResponseWithDefaults() *ConnectorStatusResponse {
	this := ConnectorStatusResponse{}
	return &this
}

// GetStatusPerMsisdn returns the StatusPerMsisdn field value if set, zero value otherwise.
func (o *ConnectorStatusResponse) GetStatusPerMsisdn() map[string]string {
	if o == nil || o.StatusPerMsisdn == nil {
		var ret map[string]string
		return ret
	}
	return *o.StatusPerMsisdn
}

// GetStatusPerMsisdnOk returns a tuple with the StatusPerMsisdn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConnectorStatusResponse) GetStatusPerMsisdnOk() (*map[string]string, bool) {
	if o == nil || o.StatusPerMsisdn == nil {
		return nil, false
	}
	return o.StatusPerMsisdn, true
}

// HasStatusPerMsisdn returns a boolean if a field has been set.
func (o *ConnectorStatusResponse) HasStatusPerMsisdn() bool {
	if o != nil && o.StatusPerMsisdn != nil {
		return true
	}

	return false
}

// SetStatusPerMsisdn gets a reference to the given map[string]string and assigns it to the StatusPerMsisdn field.
func (o *ConnectorStatusResponse) SetStatusPerMsisdn(v map[string]string) {
	o.StatusPerMsisdn = &v
}

func (o ConnectorStatusResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.StatusPerMsisdn != nil {
		toSerialize["statusPerMsisdn"] = o.StatusPerMsisdn
	}
	return json.Marshal(toSerialize)
}

type NullableConnectorStatusResponse struct {
	value *ConnectorStatusResponse
	isSet bool
}

func (v NullableConnectorStatusResponse) Get() *ConnectorStatusResponse {
	return v.value
}

func (v *NullableConnectorStatusResponse) Set(val *ConnectorStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectorStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectorStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectorStatusResponse(val *ConnectorStatusResponse) *NullableConnectorStatusResponse {
	return &NullableConnectorStatusResponse{value: val, isSet: true}
}

func (v NullableConnectorStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectorStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


