/*
 * Live Objects REST API Guide v2.13.3
 *
 * API description for Live Objects service
 *
 * API version: 2.13.3
 * Contact: liveobjects.support@orange.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package liveobjects

import (
	"encoding/json"
)

// DeviceInterface Full details about a device interface
type DeviceInterface struct {
	// Interface connector ID
	Connector *string `json:"connector,omitempty"`
	// Interface node ID
	NodeId *string `json:"nodeId,omitempty"`
	// Device identifier (URN)
	DeviceId *string `json:"deviceId,omitempty"`
	// Indicates whether the interface is enabled
	Enabled *bool `json:"enabled,omitempty"`
	// Interface status
	Status *string `json:"status,omitempty"`
	// Base definition
	Definition *map[string]interface{} `json:"definition,omitempty"`
	// Last contact date
	LastContact  *string                `json:"lastContact,omitempty"`
	Capabilities *InterfaceCapabilities `json:"capabilities,omitempty"`
	// Interface activity
	Activity *map[string]interface{} `json:"activity,omitempty"`
	// Date/time of the device creation
	Created *string `json:"created,omitempty"`
	// Date/time of the device update
	Updated *string `json:"updated,omitempty"`
}

// NewDeviceInterfaceWithDefaults instantiates a new DeviceInterface object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeviceInterfaceWithDefaults() *DeviceInterface {
	this := DeviceInterface{}
	return &this
}

// GetConnector returns the Connector field value if set, zero value otherwise.
func (o *DeviceInterface) GetConnector() string {
	if o == nil || o.Connector == nil {
		var ret string
		return ret
	}
	return *o.Connector
}

// GetConnectorOk returns a tuple with the Connector field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceInterface) GetConnectorOk() (*string, bool) {
	if o == nil || o.Connector == nil {
		return nil, false
	}
	return o.Connector, true
}

// HasConnector returns a boolean if a field has been set.
func (o *DeviceInterface) HasConnector() bool {
	if o != nil && o.Connector != nil {
		return true
	}

	return false
}

// SetConnector gets a reference to the given string and assigns it to the Connector field.
func (o *DeviceInterface) SetConnector(v string) {
	o.Connector = &v
}

// GetNodeId returns the NodeId field value if set, zero value otherwise.
func (o *DeviceInterface) GetNodeId() string {
	if o == nil || o.NodeId == nil {
		var ret string
		return ret
	}
	return *o.NodeId
}

// GetNodeIdOk returns a tuple with the NodeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceInterface) GetNodeIdOk() (*string, bool) {
	if o == nil || o.NodeId == nil {
		return nil, false
	}
	return o.NodeId, true
}

// HasNodeId returns a boolean if a field has been set.
func (o *DeviceInterface) HasNodeId() bool {
	if o != nil && o.NodeId != nil {
		return true
	}

	return false
}

// SetNodeId gets a reference to the given string and assigns it to the NodeId field.
func (o *DeviceInterface) SetNodeId(v string) {
	o.NodeId = &v
}

// GetDeviceId returns the DeviceId field value if set, zero value otherwise.
func (o *DeviceInterface) GetDeviceId() string {
	if o == nil || o.DeviceId == nil {
		var ret string
		return ret
	}
	return *o.DeviceId
}

// GetDeviceIdOk returns a tuple with the DeviceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceInterface) GetDeviceIdOk() (*string, bool) {
	if o == nil || o.DeviceId == nil {
		return nil, false
	}
	return o.DeviceId, true
}

// HasDeviceId returns a boolean if a field has been set.
func (o *DeviceInterface) HasDeviceId() bool {
	if o != nil && o.DeviceId != nil {
		return true
	}

	return false
}

// SetDeviceId gets a reference to the given string and assigns it to the DeviceId field.
func (o *DeviceInterface) SetDeviceId(v string) {
	o.DeviceId = &v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *DeviceInterface) GetEnabled() bool {
	if o == nil || o.Enabled == nil {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceInterface) GetEnabledOk() (*bool, bool) {
	if o == nil || o.Enabled == nil {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *DeviceInterface) HasEnabled() bool {
	if o != nil && o.Enabled != nil {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *DeviceInterface) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *DeviceInterface) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceInterface) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *DeviceInterface) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *DeviceInterface) SetStatus(v string) {
	o.Status = &v
}

// GetDefinition returns the Definition field value if set, zero value otherwise.
func (o *DeviceInterface) GetDefinition() map[string]interface{} {
	if o == nil || o.Definition == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.Definition
}

// GetDefinitionOk returns a tuple with the Definition field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceInterface) GetDefinitionOk() (*map[string]interface{}, bool) {
	if o == nil || o.Definition == nil {
		return nil, false
	}
	return o.Definition, true
}

// HasDefinition returns a boolean if a field has been set.
func (o *DeviceInterface) HasDefinition() bool {
	if o != nil && o.Definition != nil {
		return true
	}

	return false
}

// SetDefinition gets a reference to the given map[string]interface{} and assigns it to the Definition field.
func (o *DeviceInterface) SetDefinition(v map[string]interface{}) {
	o.Definition = &v
}

// GetLastContact returns the LastContact field value if set, zero value otherwise.
func (o *DeviceInterface) GetLastContact() string {
	if o == nil || o.LastContact == nil {
		var ret string
		return ret
	}
	return *o.LastContact
}

// GetLastContactOk returns a tuple with the LastContact field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceInterface) GetLastContactOk() (*string, bool) {
	if o == nil || o.LastContact == nil {
		return nil, false
	}
	return o.LastContact, true
}

// HasLastContact returns a boolean if a field has been set.
func (o *DeviceInterface) HasLastContact() bool {
	if o != nil && o.LastContact != nil {
		return true
	}

	return false
}

// SetLastContact gets a reference to the given string and assigns it to the LastContact field.
func (o *DeviceInterface) SetLastContact(v string) {
	o.LastContact = &v
}

// GetCapabilities returns the Capabilities field value if set, zero value otherwise.
func (o *DeviceInterface) GetCapabilities() InterfaceCapabilities {
	if o == nil || o.Capabilities == nil {
		var ret InterfaceCapabilities
		return ret
	}
	return *o.Capabilities
}

// GetCapabilitiesOk returns a tuple with the Capabilities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceInterface) GetCapabilitiesOk() (*InterfaceCapabilities, bool) {
	if o == nil || o.Capabilities == nil {
		return nil, false
	}
	return o.Capabilities, true
}

// HasCapabilities returns a boolean if a field has been set.
func (o *DeviceInterface) HasCapabilities() bool {
	if o != nil && o.Capabilities != nil {
		return true
	}

	return false
}

// SetCapabilities gets a reference to the given InterfaceCapabilities and assigns it to the Capabilities field.
func (o *DeviceInterface) SetCapabilities(v InterfaceCapabilities) {
	o.Capabilities = &v
}

// GetActivity returns the Activity field value if set, zero value otherwise.
func (o *DeviceInterface) GetActivity() map[string]interface{} {
	if o == nil || o.Activity == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.Activity
}

// GetActivityOk returns a tuple with the Activity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceInterface) GetActivityOk() (*map[string]interface{}, bool) {
	if o == nil || o.Activity == nil {
		return nil, false
	}
	return o.Activity, true
}

// HasActivity returns a boolean if a field has been set.
func (o *DeviceInterface) HasActivity() bool {
	if o != nil && o.Activity != nil {
		return true
	}

	return false
}

// SetActivity gets a reference to the given map[string]interface{} and assigns it to the Activity field.
func (o *DeviceInterface) SetActivity(v map[string]interface{}) {
	o.Activity = &v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *DeviceInterface) GetCreated() string {
	if o == nil || o.Created == nil {
		var ret string
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceInterface) GetCreatedOk() (*string, bool) {
	if o == nil || o.Created == nil {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *DeviceInterface) HasCreated() bool {
	if o != nil && o.Created != nil {
		return true
	}

	return false
}

// SetCreated gets a reference to the given string and assigns it to the Created field.
func (o *DeviceInterface) SetCreated(v string) {
	o.Created = &v
}

// GetUpdated returns the Updated field value if set, zero value otherwise.
func (o *DeviceInterface) GetUpdated() string {
	if o == nil || o.Updated == nil {
		var ret string
		return ret
	}
	return *o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeviceInterface) GetUpdatedOk() (*string, bool) {
	if o == nil || o.Updated == nil {
		return nil, false
	}
	return o.Updated, true
}

// HasUpdated returns a boolean if a field has been set.
func (o *DeviceInterface) HasUpdated() bool {
	if o != nil && o.Updated != nil {
		return true
	}

	return false
}

// SetUpdated gets a reference to the given string and assigns it to the Updated field.
func (o *DeviceInterface) SetUpdated(v string) {
	o.Updated = &v
}

func (o DeviceInterface) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Connector != nil {
		toSerialize["connector"] = o.Connector
	}
	if o.NodeId != nil {
		toSerialize["nodeId"] = o.NodeId
	}
	if o.DeviceId != nil {
		toSerialize["deviceId"] = o.DeviceId
	}
	if o.Enabled != nil {
		toSerialize["enabled"] = o.Enabled
	}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.Definition != nil {
		toSerialize["definition"] = o.Definition
	}
	if o.LastContact != nil {
		toSerialize["lastContact"] = o.LastContact
	}
	if o.Capabilities != nil {
		toSerialize["capabilities"] = o.Capabilities
	}
	if o.Activity != nil {
		toSerialize["activity"] = o.Activity
	}
	if o.Created != nil {
		toSerialize["created"] = o.Created
	}
	if o.Updated != nil {
		toSerialize["updated"] = o.Updated
	}
	return json.Marshal(toSerialize)
}

type NullableDeviceInterface struct {
	value *DeviceInterface
	isSet bool
}

func (v NullableDeviceInterface) Get() *DeviceInterface {
	return v.value
}

func (v *NullableDeviceInterface) Set(val *DeviceInterface) {
	v.value = val
	v.isSet = true
}

func (v NullableDeviceInterface) IsSet() bool {
	return v.isSet
}

func (v *NullableDeviceInterface) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeviceInterface(val *DeviceInterface) *NullableDeviceInterface {
	return &NullableDeviceInterface{value: val, isSet: true}
}

func (v NullableDeviceInterface) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeviceInterface) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
