/*
 * Live Objects REST API Guide v2.12.2
 *
 * API description for Live Objects service
 *
 * API version: 2.12.2
 * Contact: liveobjects.support@orange.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package liveobjects
// CampaignOperationStateError struct for CampaignOperationStateError
type CampaignOperationStateError struct {
	// Optional error code associated to the current underlying operation
	Code string `json:"code,omitempty"`
	// Optional device originated error details associated to the current underlying operation
	Details string `json:"details,omitempty"`
	// Optional device originated error code associated to the current underlying operation
	DeviceCode string `json:"deviceCode,omitempty"`
	// Optional error origin associated to the current underlying operation
	Origin string `json:"origin,omitempty"`
}
