/*
 * Live Objects REST API Guide v2.12.2
 *
 * API description for Live Objects service
 *
 * API version: 2.12.2
 * Contact: liveobjects.support@orange.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package liveobjects
// LoraDeviceCreateReqWeb struct for LoraDeviceCreateReqWeb
type LoraDeviceCreateReqWeb struct {
	// LoRa device activation type
	ActivationType string `json:"activationType"`
	// Application identifier (AppEUI)
	AppEUI string `json:"appEUI"`
	// Application Key (AppKey)
	AppKey string `json:"appKey"`
	ConnectivityOptions LoraConnectivityOptionsWeb `json:"connectivityOptions,omitempty"`
	// Device connectivity plan.
	ConnectivityPlan string `json:"connectivityPlan,omitempty"`
	// LoRa End-device identifier (DevEUI)
	DevEUI string `json:"devEUI"`
	// LoraDeviceUpdateReqWeb status
	DeviceStatus string `json:"deviceStatus"`
	// LoRa device encoding
	Encoding string `json:"encoding,omitempty"`
	// LoRa device name
	Name string `json:"name"`
	// LoRa device profile
	Profile string `json:"profile"`
	// List of tags, used to tag uplink from this device
	Tags []string `json:"tags,omitempty"`
}
