/*
 * Live Objects REST API Guide v2.13.3
 *
 * API description for Live Objects service
 *
 * API version: 2.13.3
 * Contact: liveobjects.support@orange.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package liveobjects

import (
	"encoding/json"
)

// TenantDayMetrics struct for TenantDayMetrics
type TenantDayMetrics struct {
	Tenant *TenantExternalView `json:"tenant,omitempty"`
	// Statistics per day
	Days *[]DayMetrics `json:"days,omitempty"`
}

// NewTenantDayMetrics instantiates a new TenantDayMetrics object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTenantDayMetrics() *TenantDayMetrics {
	this := TenantDayMetrics{}
	return &this
}

// NewTenantDayMetricsWithDefaults instantiates a new TenantDayMetrics object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTenantDayMetricsWithDefaults() *TenantDayMetrics {
	this := TenantDayMetrics{}
	return &this
}

// GetTenant returns the Tenant field value if set, zero value otherwise.
func (o *TenantDayMetrics) GetTenant() TenantExternalView {
	if o == nil || o.Tenant == nil {
		var ret TenantExternalView
		return ret
	}
	return *o.Tenant
}

// GetTenantOk returns a tuple with the Tenant field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantDayMetrics) GetTenantOk() (*TenantExternalView, bool) {
	if o == nil || o.Tenant == nil {
		return nil, false
	}
	return o.Tenant, true
}

// HasTenant returns a boolean if a field has been set.
func (o *TenantDayMetrics) HasTenant() bool {
	if o != nil && o.Tenant != nil {
		return true
	}

	return false
}

// SetTenant gets a reference to the given TenantExternalView and assigns it to the Tenant field.
func (o *TenantDayMetrics) SetTenant(v TenantExternalView) {
	o.Tenant = &v
}

// GetDays returns the Days field value if set, zero value otherwise.
func (o *TenantDayMetrics) GetDays() []DayMetrics {
	if o == nil || o.Days == nil {
		var ret []DayMetrics
		return ret
	}
	return *o.Days
}

// GetDaysOk returns a tuple with the Days field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TenantDayMetrics) GetDaysOk() (*[]DayMetrics, bool) {
	if o == nil || o.Days == nil {
		return nil, false
	}
	return o.Days, true
}

// HasDays returns a boolean if a field has been set.
func (o *TenantDayMetrics) HasDays() bool {
	if o != nil && o.Days != nil {
		return true
	}

	return false
}

// SetDays gets a reference to the given []DayMetrics and assigns it to the Days field.
func (o *TenantDayMetrics) SetDays(v []DayMetrics) {
	o.Days = &v
}

func (o TenantDayMetrics) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Tenant != nil {
		toSerialize["tenant"] = o.Tenant
	}
	if o.Days != nil {
		toSerialize["days"] = o.Days
	}
	return json.Marshal(toSerialize)
}

type NullableTenantDayMetrics struct {
	value *TenantDayMetrics
	isSet bool
}

func (v NullableTenantDayMetrics) Get() *TenantDayMetrics {
	return v.value
}

func (v *NullableTenantDayMetrics) Set(val *TenantDayMetrics) {
	v.value = val
	v.isSet = true
}

func (v NullableTenantDayMetrics) IsSet() bool {
	return v.isSet
}

func (v *NullableTenantDayMetrics) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTenantDayMetrics(val *TenantDayMetrics) *NullableTenantDayMetrics {
	return &NullableTenantDayMetrics{value: val, isSet: true}
}

func (v NullableTenantDayMetrics) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTenantDayMetrics) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


