/*
 * Live Objects REST API Guide v2.12.2
 *
 * API description for Live Objects service
 *
 * API version: 2.12.2
 * Contact: liveobjects.support@orange.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package liveobjects
// DataMatchTest struct for DataMatchTest
type DataMatchTest struct {
	// data to test the dataPredicate with
	Data map[string]interface{} `json:"data"`
	// the jsonLogic that will be used to evaluate the data
	DataPredicate map[string]interface{} `json:"dataPredicate"`
}
