/*
 * Live Objects REST API Guide v2.12.2
 *
 * API description for Live Objects service
 *
 * API version: 2.12.2
 * Contact: liveobjects.support@orange.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package liveobjects
// ActionPolicy Object describing the relationship between triggers (message or events) and actions (email, sms, fifo publish or http push)
type ActionPolicy struct {
	Actions Actions `json:"actions"`
	// Enable or disable this action policy
	Enabled bool `json:"enabled,omitempty"`
	// Id of the action policy. Set by LiveObjects, should be null on POST.
	Id string `json:"id,omitempty"`
	// The user-defined name of the action policy
	Name string `json:"name"`
	Triggers ActionTriggers `json:"triggers"`
}
