/*
 * Live Objects REST API Guide v2.12.2
 *
 * API description for Live Objects service
 *
 * API version: 2.12.2
 * Contact: liveobjects.support@orange.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package liveobjects
// LoraDeviceUpdateReqWeb struct for LoraDeviceUpdateReqWeb
type LoraDeviceUpdateReqWeb struct {
	// Application identifier (AppEUI)
	AppEUI string `json:"appEUI,omitempty"`
	// Application Key (AppKey)
	AppKey string `json:"appKey,omitempty"`
	ConnectivityOptions LoraConnectivityOptionsWeb `json:"connectivityOptions,omitempty"`
	// Device connectivity plan.
	ConnectivityPlan string `json:"connectivityPlan,omitempty"`
	// LoraDeviceUpdateReqWeb status
	DeviceStatus string `json:"deviceStatus,omitempty"`
	// LoRa device encoding
	Encoding string `json:"encoding,omitempty"`
	// LoRa device name
	Name string `json:"name,omitempty"`
	// LoRa device profile
	Profile string `json:"profile,omitempty"`
	// List of tags, used to tag uplink from this device
	Tags []string `json:"tags,omitempty"`
}
