/*
 * Live Objects REST API Guide v2.12.2
 *
 * API description for Live Objects service
 *
 * API version: 2.12.2
 * Contact: liveobjects.support@orange.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package liveobjects
// SmsAction struct for SmsAction
type SmsAction struct {
	// A raw string or a mustache (https://mustache.github.io/mustache.5.html) template describing the sms content
	ContentTemplate string `json:"contentTemplate"`
	// A list of valid msisdn
	DestinationPhoneNumbers []string `json:"destinationPhoneNumbers"`
}
