/*
 * Live Objects REST API Guide v2.12.2
 *
 * API description for Live Objects service
 *
 * API version: 2.12.2
 * Contact: liveobjects.support@orange.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package liveobjects
// PayloadDescriptionMetadata decoder metadata
type PayloadDescriptionMetadata struct {
	// the decoder is certified for the specified encoding. Only a public decoder can be certified. The default value is false.
	Certified bool `json:"certified,omitempty"`
	// date since when the decoder is certified. ISO 8601 date time.
	CertifiedSince string `json:"certifiedSince,omitempty"`
}
