/*
 * Live Objects REST API Guide v2.13.3
 *
 * API description for Live Objects service
 *
 * API version: 2.13.3
 * Contact: liveobjects.support@orange.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package liveobjects

import (
	"encoding/json"
)

// AssetParameter struct for AssetParameter
type AssetParameter struct {
	LastKnownValueTs *int64 `json:"lastKnownValueTs,omitempty"`
	TargetValue *AssetParameterValue `json:"targetValue,omitempty"`
	UpdateReqCorrelationId *int32 `json:"updateReqCorrelationId,omitempty"`
	UpdateStatus *string `json:"updateStatus,omitempty"`
	UpdateStatusTs *int64 `json:"updateStatusTs,omitempty"`
	Value *AssetParameterValue `json:"value,omitempty"`
}

// NewAssetParameter instantiates a new AssetParameter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssetParameter() *AssetParameter {
	this := AssetParameter{}
	return &this
}

// NewAssetParameterWithDefaults instantiates a new AssetParameter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssetParameterWithDefaults() *AssetParameter {
	this := AssetParameter{}
	return &this
}

// GetLastKnownValueTs returns the LastKnownValueTs field value if set, zero value otherwise.
func (o *AssetParameter) GetLastKnownValueTs() int64 {
	if o == nil || o.LastKnownValueTs == nil {
		var ret int64
		return ret
	}
	return *o.LastKnownValueTs
}

// GetLastKnownValueTsOk returns a tuple with the LastKnownValueTs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetParameter) GetLastKnownValueTsOk() (*int64, bool) {
	if o == nil || o.LastKnownValueTs == nil {
		return nil, false
	}
	return o.LastKnownValueTs, true
}

// HasLastKnownValueTs returns a boolean if a field has been set.
func (o *AssetParameter) HasLastKnownValueTs() bool {
	if o != nil && o.LastKnownValueTs != nil {
		return true
	}

	return false
}

// SetLastKnownValueTs gets a reference to the given int64 and assigns it to the LastKnownValueTs field.
func (o *AssetParameter) SetLastKnownValueTs(v int64) {
	o.LastKnownValueTs = &v
}

// GetTargetValue returns the TargetValue field value if set, zero value otherwise.
func (o *AssetParameter) GetTargetValue() AssetParameterValue {
	if o == nil || o.TargetValue == nil {
		var ret AssetParameterValue
		return ret
	}
	return *o.TargetValue
}

// GetTargetValueOk returns a tuple with the TargetValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetParameter) GetTargetValueOk() (*AssetParameterValue, bool) {
	if o == nil || o.TargetValue == nil {
		return nil, false
	}
	return o.TargetValue, true
}

// HasTargetValue returns a boolean if a field has been set.
func (o *AssetParameter) HasTargetValue() bool {
	if o != nil && o.TargetValue != nil {
		return true
	}

	return false
}

// SetTargetValue gets a reference to the given AssetParameterValue and assigns it to the TargetValue field.
func (o *AssetParameter) SetTargetValue(v AssetParameterValue) {
	o.TargetValue = &v
}

// GetUpdateReqCorrelationId returns the UpdateReqCorrelationId field value if set, zero value otherwise.
func (o *AssetParameter) GetUpdateReqCorrelationId() int32 {
	if o == nil || o.UpdateReqCorrelationId == nil {
		var ret int32
		return ret
	}
	return *o.UpdateReqCorrelationId
}

// GetUpdateReqCorrelationIdOk returns a tuple with the UpdateReqCorrelationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetParameter) GetUpdateReqCorrelationIdOk() (*int32, bool) {
	if o == nil || o.UpdateReqCorrelationId == nil {
		return nil, false
	}
	return o.UpdateReqCorrelationId, true
}

// HasUpdateReqCorrelationId returns a boolean if a field has been set.
func (o *AssetParameter) HasUpdateReqCorrelationId() bool {
	if o != nil && o.UpdateReqCorrelationId != nil {
		return true
	}

	return false
}

// SetUpdateReqCorrelationId gets a reference to the given int32 and assigns it to the UpdateReqCorrelationId field.
func (o *AssetParameter) SetUpdateReqCorrelationId(v int32) {
	o.UpdateReqCorrelationId = &v
}

// GetUpdateStatus returns the UpdateStatus field value if set, zero value otherwise.
func (o *AssetParameter) GetUpdateStatus() string {
	if o == nil || o.UpdateStatus == nil {
		var ret string
		return ret
	}
	return *o.UpdateStatus
}

// GetUpdateStatusOk returns a tuple with the UpdateStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetParameter) GetUpdateStatusOk() (*string, bool) {
	if o == nil || o.UpdateStatus == nil {
		return nil, false
	}
	return o.UpdateStatus, true
}

// HasUpdateStatus returns a boolean if a field has been set.
func (o *AssetParameter) HasUpdateStatus() bool {
	if o != nil && o.UpdateStatus != nil {
		return true
	}

	return false
}

// SetUpdateStatus gets a reference to the given string and assigns it to the UpdateStatus field.
func (o *AssetParameter) SetUpdateStatus(v string) {
	o.UpdateStatus = &v
}

// GetUpdateStatusTs returns the UpdateStatusTs field value if set, zero value otherwise.
func (o *AssetParameter) GetUpdateStatusTs() int64 {
	if o == nil || o.UpdateStatusTs == nil {
		var ret int64
		return ret
	}
	return *o.UpdateStatusTs
}

// GetUpdateStatusTsOk returns a tuple with the UpdateStatusTs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetParameter) GetUpdateStatusTsOk() (*int64, bool) {
	if o == nil || o.UpdateStatusTs == nil {
		return nil, false
	}
	return o.UpdateStatusTs, true
}

// HasUpdateStatusTs returns a boolean if a field has been set.
func (o *AssetParameter) HasUpdateStatusTs() bool {
	if o != nil && o.UpdateStatusTs != nil {
		return true
	}

	return false
}

// SetUpdateStatusTs gets a reference to the given int64 and assigns it to the UpdateStatusTs field.
func (o *AssetParameter) SetUpdateStatusTs(v int64) {
	o.UpdateStatusTs = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *AssetParameter) GetValue() AssetParameterValue {
	if o == nil || o.Value == nil {
		var ret AssetParameterValue
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetParameter) GetValueOk() (*AssetParameterValue, bool) {
	if o == nil || o.Value == nil {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *AssetParameter) HasValue() bool {
	if o != nil && o.Value != nil {
		return true
	}

	return false
}

// SetValue gets a reference to the given AssetParameterValue and assigns it to the Value field.
func (o *AssetParameter) SetValue(v AssetParameterValue) {
	o.Value = &v
}

func (o AssetParameter) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.LastKnownValueTs != nil {
		toSerialize["lastKnownValueTs"] = o.LastKnownValueTs
	}
	if o.TargetValue != nil {
		toSerialize["targetValue"] = o.TargetValue
	}
	if o.UpdateReqCorrelationId != nil {
		toSerialize["updateReqCorrelationId"] = o.UpdateReqCorrelationId
	}
	if o.UpdateStatus != nil {
		toSerialize["updateStatus"] = o.UpdateStatus
	}
	if o.UpdateStatusTs != nil {
		toSerialize["updateStatusTs"] = o.UpdateStatusTs
	}
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableAssetParameter struct {
	value *AssetParameter
	isSet bool
}

func (v NullableAssetParameter) Get() *AssetParameter {
	return v.value
}

func (v *NullableAssetParameter) Set(val *AssetParameter) {
	v.value = val
	v.isSet = true
}

func (v NullableAssetParameter) IsSet() bool {
	return v.isSet
}

func (v *NullableAssetParameter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssetParameter(val *AssetParameter) *NullableAssetParameter {
	return &NullableAssetParameter{value: val, isSet: true}
}

func (v NullableAssetParameter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssetParameter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


