/*
 * Live Objects REST API Guide v2.12.2
 *
 * API description for Live Objects service
 *
 * API version: 2.12.2
 * Contact: liveobjects.support@orange.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package liveobjects
// ActivityState defines the current activity state of a specific device and a specific activity rule
type ActivityState struct {
	ActivityRule ActivityRule `json:"activityRule"`
	// id of the targeted device
	DeviceId string `json:"deviceId"`
	// timestamp (ISO 8601) of the last registered contact of the device
	LastActivity string `json:"lastActivity,omitempty"`
	// timestamp (ISO 8601) of the next alarm for this rule if the device remains silent
	NextAlarm string `json:"nextAlarm"`
	// number of times a reminder has been sent for the current state
	NumberOfAlarmReminders int32 `json:"numberOfAlarmReminders"`
	// current state of the device
	State string `json:"state"`
}
