/*
 * Live Objects REST API Guide v2.12.2
 *
 * API description for Live Objects service
 *
 * API version: 2.12.2
 * Contact: liveobjects.support@orange.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package liveobjects
// TenantExternalView struct for TenantExternalView
type TenantExternalView struct {
	// tenant Id
	Id string `json:"id,omitempty"`
	// tenant name
	Name string `json:"name,omitempty"`
	OfferAndOptions OfferAndOptions `json:"offerAndOptions,omitempty"`
	// tenant properties
	Properties map[string]string `json:"properties,omitempty"`
}
