/*
 * Live Objects REST API Guide v2.13.3
 *
 * API description for Live Objects service
 *
 * API version: 2.13.3
 * Contact: liveobjects.support@orange.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package liveobjects

import (
	"encoding/json"
)

// LoraGatewayLocation struct for LoraGatewayLocation
type LoraGatewayLocation struct {
	// Last geolocation altitude (meter)
	Alt *float64 `json:"alt,omitempty"`
	// Date/time of the last location
	LastUpdateTs *string `json:"lastUpdateTs,omitempty"`
	// Last geolocation latitude (GPS coordinate system)
	Lat *float64 `json:"lat,omitempty"`
	// Last geolocation longitude (GPS coordinate system)
	Lon *float64 `json:"lon,omitempty"`
	// Computing geolocation method
	Provider *string `json:"provider,omitempty"`
}

// NewLoraGatewayLocation instantiates a new LoraGatewayLocation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoraGatewayLocation() *LoraGatewayLocation {
	this := LoraGatewayLocation{}
	return &this
}

// NewLoraGatewayLocationWithDefaults instantiates a new LoraGatewayLocation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoraGatewayLocationWithDefaults() *LoraGatewayLocation {
	this := LoraGatewayLocation{}
	return &this
}

// GetAlt returns the Alt field value if set, zero value otherwise.
func (o *LoraGatewayLocation) GetAlt() float64 {
	if o == nil || o.Alt == nil {
		var ret float64
		return ret
	}
	return *o.Alt
}

// GetAltOk returns a tuple with the Alt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoraGatewayLocation) GetAltOk() (*float64, bool) {
	if o == nil || o.Alt == nil {
		return nil, false
	}
	return o.Alt, true
}

// HasAlt returns a boolean if a field has been set.
func (o *LoraGatewayLocation) HasAlt() bool {
	if o != nil && o.Alt != nil {
		return true
	}

	return false
}

// SetAlt gets a reference to the given float64 and assigns it to the Alt field.
func (o *LoraGatewayLocation) SetAlt(v float64) {
	o.Alt = &v
}

// GetLastUpdateTs returns the LastUpdateTs field value if set, zero value otherwise.
func (o *LoraGatewayLocation) GetLastUpdateTs() string {
	if o == nil || o.LastUpdateTs == nil {
		var ret string
		return ret
	}
	return *o.LastUpdateTs
}

// GetLastUpdateTsOk returns a tuple with the LastUpdateTs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoraGatewayLocation) GetLastUpdateTsOk() (*string, bool) {
	if o == nil || o.LastUpdateTs == nil {
		return nil, false
	}
	return o.LastUpdateTs, true
}

// HasLastUpdateTs returns a boolean if a field has been set.
func (o *LoraGatewayLocation) HasLastUpdateTs() bool {
	if o != nil && o.LastUpdateTs != nil {
		return true
	}

	return false
}

// SetLastUpdateTs gets a reference to the given string and assigns it to the LastUpdateTs field.
func (o *LoraGatewayLocation) SetLastUpdateTs(v string) {
	o.LastUpdateTs = &v
}

// GetLat returns the Lat field value if set, zero value otherwise.
func (o *LoraGatewayLocation) GetLat() float64 {
	if o == nil || o.Lat == nil {
		var ret float64
		return ret
	}
	return *o.Lat
}

// GetLatOk returns a tuple with the Lat field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoraGatewayLocation) GetLatOk() (*float64, bool) {
	if o == nil || o.Lat == nil {
		return nil, false
	}
	return o.Lat, true
}

// HasLat returns a boolean if a field has been set.
func (o *LoraGatewayLocation) HasLat() bool {
	if o != nil && o.Lat != nil {
		return true
	}

	return false
}

// SetLat gets a reference to the given float64 and assigns it to the Lat field.
func (o *LoraGatewayLocation) SetLat(v float64) {
	o.Lat = &v
}

// GetLon returns the Lon field value if set, zero value otherwise.
func (o *LoraGatewayLocation) GetLon() float64 {
	if o == nil || o.Lon == nil {
		var ret float64
		return ret
	}
	return *o.Lon
}

// GetLonOk returns a tuple with the Lon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoraGatewayLocation) GetLonOk() (*float64, bool) {
	if o == nil || o.Lon == nil {
		return nil, false
	}
	return o.Lon, true
}

// HasLon returns a boolean if a field has been set.
func (o *LoraGatewayLocation) HasLon() bool {
	if o != nil && o.Lon != nil {
		return true
	}

	return false
}

// SetLon gets a reference to the given float64 and assigns it to the Lon field.
func (o *LoraGatewayLocation) SetLon(v float64) {
	o.Lon = &v
}

// GetProvider returns the Provider field value if set, zero value otherwise.
func (o *LoraGatewayLocation) GetProvider() string {
	if o == nil || o.Provider == nil {
		var ret string
		return ret
	}
	return *o.Provider
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoraGatewayLocation) GetProviderOk() (*string, bool) {
	if o == nil || o.Provider == nil {
		return nil, false
	}
	return o.Provider, true
}

// HasProvider returns a boolean if a field has been set.
func (o *LoraGatewayLocation) HasProvider() bool {
	if o != nil && o.Provider != nil {
		return true
	}

	return false
}

// SetProvider gets a reference to the given string and assigns it to the Provider field.
func (o *LoraGatewayLocation) SetProvider(v string) {
	o.Provider = &v
}

func (o LoraGatewayLocation) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Alt != nil {
		toSerialize["alt"] = o.Alt
	}
	if o.LastUpdateTs != nil {
		toSerialize["lastUpdateTs"] = o.LastUpdateTs
	}
	if o.Lat != nil {
		toSerialize["lat"] = o.Lat
	}
	if o.Lon != nil {
		toSerialize["lon"] = o.Lon
	}
	if o.Provider != nil {
		toSerialize["provider"] = o.Provider
	}
	return json.Marshal(toSerialize)
}

type NullableLoraGatewayLocation struct {
	value *LoraGatewayLocation
	isSet bool
}

func (v NullableLoraGatewayLocation) Get() *LoraGatewayLocation {
	return v.value
}

func (v *NullableLoraGatewayLocation) Set(val *LoraGatewayLocation) {
	v.value = val
	v.isSet = true
}

func (v NullableLoraGatewayLocation) IsSet() bool {
	return v.isSet
}

func (v *NullableLoraGatewayLocation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoraGatewayLocation(val *LoraGatewayLocation) *NullableLoraGatewayLocation {
	return &NullableLoraGatewayLocation{value: val, isSet: true}
}

func (v NullableLoraGatewayLocation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoraGatewayLocation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


