/*
 * Live Objects REST API Guide v2.12.2
 *
 * API description for Live Objects service
 *
 * API version: 2.12.2
 * Contact: liveobjects.support@orange.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package liveobjects
// PartnerToken struct for PartnerToken
type PartnerToken struct {
	// The token that your application sends to authorize a Live Objects API request.
	AccessToken string `json:"access_token,omitempty"`
	// The remaining lifetime of the access token in seconds.
	ExpiresIn int64 `json:"expires_in,omitempty"`
	// The type of token returned
	TokenType string `json:"token_type,omitempty"`
}
