/*
 * Live Objects REST API Guide v2.12.2
 *
 * API description for Live Objects service
 *
 * API version: 2.12.2
 * Contact: liveobjects.support@orange.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package liveobjects
// CommandResponse struct for CommandResponse
type CommandResponse struct {
	// command response value (protocol/connector-dependant)
	Value map[string]interface{} `json:"value"`
}
