/*
 * Live Objects REST API Guide v2.13.3
 *
 * API description for Live Objects service
 *
 * API version: 2.13.3
 * Contact: liveobjects.support@orange.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package liveobjects

import (
	"encoding/json"
)

// UpdatePasswordReqWeb User Update Password body Request
type UpdatePasswordReqWeb struct {
	// security captcha got from user
	Captcha string `json:"captcha"`
	// captcha token, that will be checked for authorizing the update
	CaptchaToken string `json:"captchaToken"`
	// new password string
	NewPassword string `json:"newPassword"`
	// old password string
	OldPassword string `json:"oldPassword"`
	// token identifier
	TokenId string `json:"tokenId"`
}

// NewUpdatePasswordReqWeb instantiates a new UpdatePasswordReqWeb object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdatePasswordReqWeb(captcha string, captchaToken string, newPassword string, oldPassword string, tokenId string, ) *UpdatePasswordReqWeb {
	this := UpdatePasswordReqWeb{}
	this.Captcha = captcha
	this.CaptchaToken = captchaToken
	this.NewPassword = newPassword
	this.OldPassword = oldPassword
	this.TokenId = tokenId
	return &this
}

// NewUpdatePasswordReqWebWithDefaults instantiates a new UpdatePasswordReqWeb object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdatePasswordReqWebWithDefaults() *UpdatePasswordReqWeb {
	this := UpdatePasswordReqWeb{}
	return &this
}

// GetCaptcha returns the Captcha field value
func (o *UpdatePasswordReqWeb) GetCaptcha() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Captcha
}

// GetCaptchaOk returns a tuple with the Captcha field value
// and a boolean to check if the value has been set.
func (o *UpdatePasswordReqWeb) GetCaptchaOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Captcha, true
}

// SetCaptcha sets field value
func (o *UpdatePasswordReqWeb) SetCaptcha(v string) {
	o.Captcha = v
}

// GetCaptchaToken returns the CaptchaToken field value
func (o *UpdatePasswordReqWeb) GetCaptchaToken() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.CaptchaToken
}

// GetCaptchaTokenOk returns a tuple with the CaptchaToken field value
// and a boolean to check if the value has been set.
func (o *UpdatePasswordReqWeb) GetCaptchaTokenOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.CaptchaToken, true
}

// SetCaptchaToken sets field value
func (o *UpdatePasswordReqWeb) SetCaptchaToken(v string) {
	o.CaptchaToken = v
}

// GetNewPassword returns the NewPassword field value
func (o *UpdatePasswordReqWeb) GetNewPassword() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.NewPassword
}

// GetNewPasswordOk returns a tuple with the NewPassword field value
// and a boolean to check if the value has been set.
func (o *UpdatePasswordReqWeb) GetNewPasswordOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.NewPassword, true
}

// SetNewPassword sets field value
func (o *UpdatePasswordReqWeb) SetNewPassword(v string) {
	o.NewPassword = v
}

// GetOldPassword returns the OldPassword field value
func (o *UpdatePasswordReqWeb) GetOldPassword() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.OldPassword
}

// GetOldPasswordOk returns a tuple with the OldPassword field value
// and a boolean to check if the value has been set.
func (o *UpdatePasswordReqWeb) GetOldPasswordOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.OldPassword, true
}

// SetOldPassword sets field value
func (o *UpdatePasswordReqWeb) SetOldPassword(v string) {
	o.OldPassword = v
}

// GetTokenId returns the TokenId field value
func (o *UpdatePasswordReqWeb) GetTokenId() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.TokenId
}

// GetTokenIdOk returns a tuple with the TokenId field value
// and a boolean to check if the value has been set.
func (o *UpdatePasswordReqWeb) GetTokenIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.TokenId, true
}

// SetTokenId sets field value
func (o *UpdatePasswordReqWeb) SetTokenId(v string) {
	o.TokenId = v
}

func (o UpdatePasswordReqWeb) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["captcha"] = o.Captcha
	}
	if true {
		toSerialize["captchaToken"] = o.CaptchaToken
	}
	if true {
		toSerialize["newPassword"] = o.NewPassword
	}
	if true {
		toSerialize["oldPassword"] = o.OldPassword
	}
	if true {
		toSerialize["tokenId"] = o.TokenId
	}
	return json.Marshal(toSerialize)
}

type NullableUpdatePasswordReqWeb struct {
	value *UpdatePasswordReqWeb
	isSet bool
}

func (v NullableUpdatePasswordReqWeb) Get() *UpdatePasswordReqWeb {
	return v.value
}

func (v *NullableUpdatePasswordReqWeb) Set(val *UpdatePasswordReqWeb) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdatePasswordReqWeb) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdatePasswordReqWeb) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdatePasswordReqWeb(val *UpdatePasswordReqWeb) *NullableUpdatePasswordReqWeb {
	return &NullableUpdatePasswordReqWeb{value: val, isSet: true}
}

func (v NullableUpdatePasswordReqWeb) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdatePasswordReqWeb) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


