/*
 * Live Objects REST API Guide v2.13.3
 *
 * API description for Live Objects service
 *
 * API version: 2.13.3
 * Contact: liveobjects.support@orange.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package liveobjects

import (
	"encoding/json"
)

// PageableResourceUpdateWeb struct for PageableResourceUpdateWeb
type PageableResourceUpdateWeb struct {
	// number of the current page: starts at 0.
	Page int64 `json:"page"`
	// number of data per page (= maximum number of data in the associated list of data:the last page can have less data)
	Size int64 `json:"size"`
	// total count of data in the complete list.
	TotalCount int64 `json:"totalCount"`
	// list of data in this page.
	Data []ResourceUpdateWeb `json:"data"`
}

// NewPageableResourceUpdateWeb instantiates a new PageableResourceUpdateWeb object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPageableResourceUpdateWeb(page int64, size int64, totalCount int64, data []ResourceUpdateWeb, ) *PageableResourceUpdateWeb {
	this := PageableResourceUpdateWeb{}
	this.Page = page
	this.Size = size
	this.TotalCount = totalCount
	this.Data = data
	return &this
}

// NewPageableResourceUpdateWebWithDefaults instantiates a new PageableResourceUpdateWeb object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPageableResourceUpdateWebWithDefaults() *PageableResourceUpdateWeb {
	this := PageableResourceUpdateWeb{}
	return &this
}

// GetPage returns the Page field value
func (o *PageableResourceUpdateWeb) GetPage() int64 {
	if o == nil  {
		var ret int64
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *PageableResourceUpdateWeb) GetPageOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *PageableResourceUpdateWeb) SetPage(v int64) {
	o.Page = v
}

// GetSize returns the Size field value
func (o *PageableResourceUpdateWeb) GetSize() int64 {
	if o == nil  {
		var ret int64
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *PageableResourceUpdateWeb) GetSizeOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *PageableResourceUpdateWeb) SetSize(v int64) {
	o.Size = v
}

// GetTotalCount returns the TotalCount field value
func (o *PageableResourceUpdateWeb) GetTotalCount() int64 {
	if o == nil  {
		var ret int64
		return ret
	}

	return o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value
// and a boolean to check if the value has been set.
func (o *PageableResourceUpdateWeb) GetTotalCountOk() (*int64, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.TotalCount, true
}

// SetTotalCount sets field value
func (o *PageableResourceUpdateWeb) SetTotalCount(v int64) {
	o.TotalCount = v
}

// GetData returns the Data field value
func (o *PageableResourceUpdateWeb) GetData() []ResourceUpdateWeb {
	if o == nil  {
		var ret []ResourceUpdateWeb
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *PageableResourceUpdateWeb) GetDataOk() (*[]ResourceUpdateWeb, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *PageableResourceUpdateWeb) SetData(v []ResourceUpdateWeb) {
	o.Data = v
}

func (o PageableResourceUpdateWeb) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["page"] = o.Page
	}
	if true {
		toSerialize["size"] = o.Size
	}
	if true {
		toSerialize["totalCount"] = o.TotalCount
	}
	if true {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullablePageableResourceUpdateWeb struct {
	value *PageableResourceUpdateWeb
	isSet bool
}

func (v NullablePageableResourceUpdateWeb) Get() *PageableResourceUpdateWeb {
	return v.value
}

func (v *NullablePageableResourceUpdateWeb) Set(val *PageableResourceUpdateWeb) {
	v.value = val
	v.isSet = true
}

func (v NullablePageableResourceUpdateWeb) IsSet() bool {
	return v.isSet
}

func (v *NullablePageableResourceUpdateWeb) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePageableResourceUpdateWeb(val *PageableResourceUpdateWeb) *NullablePageableResourceUpdateWeb {
	return &NullablePageableResourceUpdateWeb{value: val, isSet: true}
}

func (v NullablePageableResourceUpdateWeb) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePageableResourceUpdateWeb) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


